language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
notifications:
  email: false
deploy:
    provider: heroku
    api_key:
        secure: VmO3s6JuDH7+azjwuZX5LGPGgIDiGGfng7GBn4Ar/TQi3erOR4PIvR3JzKmHQ4dSUW24QNsshgbTqNsZcThRYZMsqy8qnA4NBgPxiypp/6xh+IC5k2Bqg8c1mOF4ki84teMOL+AtaIxdffm5Mn9/POnPJ3p1GWXn07yki5XysLHL+z8FGb5y0NBbkHLi3ugtIwmwh0M/h9s/4Su7GoCGPRjcz2RJIEZWwljbsBN3A0ePE1VdcPt8nW306Vzr98VZ2hSwrrDjD9ipClKFf1Rd3KRXheTx8c2nL/TI2a8dGwJOicTxqW4ykDMroZcsk5Ki9yeB9MtfQZ1bCjVqnn791bS1nFlELzRgzwSUjDoFXfAGPS8Dqigg4KK+YBd4KAnlizbULkvO2Yrw+s8ivA5JSfACwbkrqG5gw8b2BnMiqst3NVRiopYCImvu2plH5+Z256wblI9JvzowQPHkPKCi9axOrDos5NFdldHRPnJ1ggVmTHO1zLpzV928Bik5lMYXdYBabWBRdGyji5EknKHxOKM0sSpipLwxECwwJiEtfzfNL5Mgf/50epmx5Hyhq3htF730/NfO917690YYDjjps7adEP2zr1WTUyQyWSAsjsR0w6VvKyXtTBBUr5c0iSQaZlP6AHeO1V4q3iZsmKX2h4dfcJOzqdNQ+F7B61GDzZQ=
    app: warm-peak-85048
